---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
spec:
  chartRef:
    kind: OCIRepository
    name: snapshot-controller
  interval: 1h
  values:
    volumeSnapshotClasses:
      - name: csi-ceph-blockpool
        driver: rook-ceph.rbd.csi.ceph.com
        annotations:
          snapshot.storage.kubernetes.io/is-default-class: "true"
        parameters:
          clusterID: rook-ceph
          csi.storage.k8s.io/snapshotter-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph
        deletionPolicy: Delete
    controller:
      replicaCount: 2
      serviceMonitor:
        create: true
    webhook:
      enabled: false
